### ISSUE TITLE
How about add turbocolor in benchmarks?

### ISSUE THREAD

**Issue by poppinlp** [lukeed/kleur#11]
Seems [turbocolor](https://github.com/jorgebucaran/turbocolor) is faster in its [benchmarks](https://github.com/jorgebucaran/turbocolor/tree/master/bench) :)

**Comment by lukeed** [comment]
Hah, momentarily 😉 It's the same code as `kleur` anyway,  sans `util.format` and a check for multiline text. Both of which "cost" ops.

**Comment by lukeed** [comment]
Fixed in 2.0.0

**Comment by poppinlp** [comment]
Nice job! Thanks~
