### ISSUE TITLE
Can't upgrade to Kleur@3 (error message from hell)

### ISSUE THREAD

**Issue by mikael1000** [lukeed/kleur#17]
The last two days i get the deprecated message ...and I don't want to "_suffer the deprecation notice on older kleur versions_". But I cant install it following the install instructions. The deprecation notice just returns next time I try to install something.

And I don't even know what this kleur is or why I have it or why I need it. Or if I should install it??

**Comment by lukeed** [comment]
You should be able to install the latest version just fine. Sounds like you have caching or some lockfile that keeps resolving to kleur@2

Try uninstalling whatever version you have then reinstalling. The deprecation is not on 3.0

**Comment by lukeed** [comment]
Just revisited this on all major `npm` versions. Everything checks out correctly for 3.0 👍 

If you're still seeing the deprecation message after updating your _direct_ dependency to `3.0.0`, then another one of your dependencies is using `kleur@2`

Nothing more I can do here, sorry 😬 Package authors need to update
