### ISSUE TITLE
Export interfaces in definition file

### ISSUE THREAD

**Issue by Hammster** [lukeed/kleur#22]
Hi, there great lib!

Currently, only the object signature `Kleur & { enabled: boolean }` is exported, it would be nice to also be able to access the interfaces for `Kleur` and `Color` directly.

**Comment by lukeed** [comment]
Hey, thanks~! Sure, I can do that :) 

Though, do you know if it conflicts with the `export = kleur;` type? To me, this `export =` form looks like it's _meant_ to say there's only one definition to be exported...but I don't use TS so not sure.

> Hoping @marvinhagemeister, the resident TS expert, could weigh in 😆

**Comment by Hammster** [comment]
I changes the definition file and tested it against my project, it should still have the same functionality as before.
