### ISSUE TITLE
Missing bold import in nested methods example

### ISSUE THREAD

**Issue by DanielRuf** [lukeed/kleur#24]
https://github.com/lukeed/kleur#nested-methods

```
const { yellow, red, cyan } = require('kleur');

console.log(yellow(`foo ${red().bold('red')} bar ${cyan('cyan')} baz`));
console.log(yellow('foo ' + red().bold('red') + ' bar ' + cyan('cyan') + ' baz'));
```

**Comment by lukeed** [comment]
Hey~! Not exactly sure what you're trying to point out here, sorry.

The code snippet runs as presented. There's no missing import.

Are you saying that my screenshot doesn't include bolded text? It does, it's just hard to see given the short strings & my terminal font doesn't have a dramatic difference.

Here's the code snippet run again:

<img width="788" alt="Screen Shot 2019-04-30 at 9 56 13 AM" src="https://user-images.githubusercontent.com/5855893/56979257-34cc9080-6b2e-11e9-9463-a2cd4292a121.png">

**Comment by DanielRuf** [comment]
Well but the `require` statement does not include `bold` so where does this come from then?

**Comment by lukeed** [comment]
Perhaps you're misreading it? There's no chain that _starts with_ `bold()`

**Comment by DanielRuf** [comment]
Then the first example is just confusing as it imports `bold` and does not mention that it is not needed in this case.

https://github.com/lukeed/kleur/blob/master/readme.md#usage

**Comment by lukeed** [comment]
Wait, ok hold on, haha

Each snippet is a separate sandbox.

The `Usage` example also works on its own. It's self-contained.

```js
// Example: Usage 
// ---
const { red, white, blue, bold } = require('kleur');

// basic usage
red('red text');
// ^

// chained methods
blue().bold().underline('howdy partner');
// ^

// nested methods
bold(`${ white().bgRed('[ERROR]') } ${ red().italic('Something happened')}`);
// ^        ^                            ^
```

```js
// Example: Nested Methods
// ---
const { yellow, red, cyan } = require('kleur');

console.log(yellow(`foo ${red().bold('red')} bar ${cyan('cyan')} baz`));
//          ^             ^                        ^
console.log(yellow('foo ' + red().bold('red') + ' bar ' + cyan('cyan') + ' baz'));
//          ^               ^                              ^
```

In this second example (the one you opened the issue for), `bold()` is available because it was returned from `red()` ➡️ `red().bold('red')`

When a "chain segment" is not given a string to paint, it continues the chain. 

For the same reason, I can do this:

```js
const { red } = require('kleur');

red().bold().underline().bgBlack('I will be red, bolded, and underlined with black background');
```

In the `chalk`-world, it would be identical to this:

```js
const { red } = require('chalk');

red.bold.underline.bgBlack('I will be red, bolded, and underlined with black background');
```

Does that clarify things a little bit more?

**Comment by DanielRuf** [comment]
Yes, this clarifies it. I just wanted to point out that the docs could describe this better as this is not mentioned there.

**Comment by lukeed** [comment]
Gotcha, thanks. I'll make a note to pass thru the text at a later point 👍
