### ISSUE TITLE
Updating benchmark

### ISSUE THREAD

**Issue by fraxken** [lukeed/kleur#27]
Hi,

I recently noticed that chalk published a new major release (v3) (with a good enhancement around performance issues). And ainsi-colors is v4 now too.

Benchmark result on my computer
```
# All Colors
  ansi-colors x 144,685 ops/sec ±1.63% (86 runs sampled)
  chalk x 475,976 ops/sec ±2.17% (85 runs sampled)
  kleur x 551,656 ops/sec ±2.41% (86 runs sampled)

# Stacked colors
  ansi-colors x 19,153 ops/sec ±1.10% (86 runs sampled)
  chalk x 367,395 ops/sec ±3.02% (79 runs sampled)
  kleur x 66,077 ops/sec ±1.47% (83 runs sampled)

# Nested colors
  ansi-colors x 53,458 ops/sec ±0.81% (88 runs sampled)
  chalk x 95,860 ops/sec ±1.86% (86 runs sampled)
  kleur x 105,228 ops/sec ±0.98% (88 runs sampled)
```

Sorry to open issue for that kind of stuff ^^. But I told myself that anyway someone would surely come one day for this haha :) 

Best Regards,
Thomas

**Comment by lukeed** [comment]
Hey, thanks! That's awesome, congrats to Chalk 😄 

Pushed a commit that updated the benchmark's results & versions.
Thanks again~
