### ISSUE TITLE
Do we have an API to create a different kleur instances

### ISSUE THREAD

**Issue by ai** [lukeed/kleur#34]
For Logux I need a way to have color output in one part and not having it in other.

```js
const a = new HumanReporter({ color: false })
const b = new HumanReporter({ color: true })

a.print()
b.print()
a.print()
```

Do we have in Kleur a way to do it?

**Comment by lukeed** [comment]
No, sorry. It's a single module that exists within a single scope. You would have to do what you were doing inside PostCSS and  do something like:

```js
if (opts.color) {
  value = kleur.red().bold(value);
}
console.log(value);
```

**Comment by ai** [comment]
Thanks :+1:
