### ISSUE TITLE
Using kleur as tagged function returns array-like string

### ISSUE THREAD

**Issue by BubuAnabelas** [lukeed/kleur#7]
I'm planning to switch from chalk to kleur on [markcat](https://github.com/bubuanabelas/markcat) but when testing kleur to see if I could do a simple "replace all" I came across the next bug (don't know if its actually a bug since I didn't read the code to understand it)

When doing everything works as expected:
```javascript
const kleur = require('kleur')
const text = kleur.red(`Hello World`)
Buffer.from(text) // <Buffer 1b 5b 33 31 6d 48 65 6c 6c 6f 20 77 6f 72 6c 64 1b 5b 33 39 6d>
```

But when I use `kleur.red` as a tagged function I get the following:
```javascript
const kleur = require('kleur')
const text = kleur.red`Hello World`
Buffer.from(text) // <Buffer 1b 5b 33 31 6d 5b 20 27 48 65 6c 6c 6f 20 77 6f 72 6c 64 27 20 5d 1b 5b 33 39 6d>
```
which looks like a red string (the typeof is string indeed) that says `[ 'Hello World' ]`.

**Comment by lukeed** [comment]
Hey, cool!

Kleur does not offer/function as a tagged template function & is without plans to support it.

Sorry about that! You may enjoy the printf behavior instead

**Comment by BubuAnabelas** [comment]
I just wanted to say that this has been changed and now works!

**Comment by BubuAnabelas** [comment]
Using kleur 3.0.0 and node 10.14.1 I get this:

```javascript
kleur.inverse`hello`; //'\u001b[7mhello\u001b[27m'

kleur.inverse(['hello']); //'\u001b[7mhello\u001b[27m'
```

And using the example I provided above:

```javascript
const kleur = require('kleur')
const text = kleur.red(`Hello World`)
Buffer.from(text) // <Buffer 1b 5b 33 31 6d 48 65 6c 6c 6f 20 57 6f 72 6c 64 1b 5b 33 39 6d>

const text2 = kleur.red`Hello World`
Buffer.from(text2) //<Buffer 1b 5b 33 31 6d 48 65 6c 6c 6f 20 57 6f 72 6c 64 1b 5b 33 39 6d>
```
